### ISSUE TITLE
Getting error while training the SeqGAN model

### ISSUE THREAD

**Issue by felixgwu** [geek-ai/Texygen#3]
Hi,

I got the following error when training the SeqGAN model.

```
epoch:13
[1.1808003]
[1.1286035]
[1.1499095]
epoch:14
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    parse_cmd(sys.argv[1:])
  File "main.py", line 69, in parse_cmd
    gan.train_oracle()
  File "path/to/Texygen/models/seqgan/Seqgan.py", line 131, in train_oracle
    self.train_discriminator()
  File "path/to/Texygen/models/seqgan/Seqgan.py", line 52, in train_discriminator
    self.dis_data_loader.load_train_data(self.oracle_file, self.generator_file)
  File "path/to/Texygen/models/seqgan/SeqganDataLoader.py", line 70, in load_train_data
    self.labels = np.concatenate([positive_labels, negative_labels], 0)
ValueError: all the input arrays must have same number of dimensions
```

The command I ran is
```sh
python main.py -g seqgan
```

Do you have any idea how it happens or how to fix it?
Thanks in advance.

**Comment by Yaoming95** [comment]
Hi, are you running the original Texygen with Python3? Seems your generator fails to output text, could you please show me your 'save/generator.txt'?

**Comment by felixgwu** [comment]
Thanks! It works perfectly now. I think there was some i/o issue last time I ran it.
